<?php

namespace ridesoft\Boiler\includes;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-07-02 at 17:06:20.
 */
class initTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var init
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new \ridesoft\Boiler\includes\init;
        $this->assertInstanceOf('ridesoft\Boiler\includes\init', $this->object);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers ridesoft\Boiler\includes\init::start
     * @todo   Implement testStart().
     */
    public function testStart() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ridesoft\Boiler\includes\init::__set
     * @todo   Implement test__set().
     */
    public function test__set() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ridesoft\Boiler\includes\init::__get
     * @todo   Implement test__get().
     */
    public function test__get() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ridesoft\Boiler\includes\init::loader
     * @todo   Implement testLoader().
     */
    public function testLoader() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
