<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-06-26 at 11:42:08.
 */
class ManagerServiceTest extends PHPUnit_Framework_TestCase {

    /**
     * @var ManagerService
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new ManagerService;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers ManagerService::getIDService
     * @todo   Implement testGetIDService().
     */
    public function testGetIDService() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ManagerService::getIDSection
     * @todo   Implement testGetIDSection().
     */
    public function testGetIDSection() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ManagerService::getSectionName
     * @todo   Implement testGetSectionName().
     */
    public function testGetSectionName() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ManagerService::getSectionDescription
     * @todo   Implement testGetSectionDescription().
     */
    public function testGetSectionDescription() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ManagerService::getSectionOrder
     * @todo   Implement testGetSectionOrder().
     */
    public function testGetSectionOrder() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ManagerService::getSectionLink
     * @todo   Implement testGetSectionLink().
     */
    public function testGetSectionLink() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ManagerService::getServiceName
     * @todo   Implement testGetServiceName().
     */
    public function testGetServiceName() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ManagerService::getServiceLink
     * @todo   Implement testGetServiceLink().
     */
    public function testGetServiceLink() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ManagerService::getServiceDescription
     * @todo   Implement testGetServiceDescription().
     */
    public function testGetServiceDescription() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ManagerService::getServiceOrder
     * @todo   Implement testGetServiceOrder().
     */
    public function testGetServiceOrder() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ManagerService::__construct1
     * @todo   Implement test__construct1().
     */
    public function test__construct1() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ManagerService::__sleep
     * @todo   Implement test__sleep().
     */
    public function test__sleep() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ManagerService::__wakeup
     * @todo   Implement test__wakeup().
     */
    public function test__wakeup() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
