<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-06-26 at 11:42:09.
 */
class ManagerUserTest extends PHPUnit_Framework_TestCase {

    /**
     * @var ManagerUser
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new ManagerUser;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers ManagerUser::getIDUser
     * @todo   Implement testGetIDUser().
     */
    public function testGetIDUser() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ManagerUser::getName
     * @todo   Implement testGetName().
     */
    public function testGetName() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ManagerUser::getSurname
     * @todo   Implement testGetSurname().
     */
    public function testGetSurname() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ManagerUser::getEmail
     * @todo   Implement testGetEmail().
     */
    public function testGetEmail() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ManagerUser::getPassword
     * @todo   Implement testGetPassword().
     */
    public function testGetPassword() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ManagerUser::getState
     * @todo   Implement testGetState().
     */
    public function testGetState() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ManagerUser::getIDType
     * @todo   Implement testGetIDType().
     */
    public function testGetIDType() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ManagerUser::getTypeName
     * @todo   Implement testGetTypeName().
     */
    public function testGetTypeName() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ManagerUser::getServices
     * @todo   Implement testGetServices().
     */
    public function testGetServices() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ManagerUser::getService
     * @todo   Implement testGetService().
     */
    public function testGetService() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ManagerUser::setServices
     * @todo   Implement testSetServices().
     */
    public function testSetServices() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ManagerUser::__construct1
     * @todo   Implement test__construct1().
     */
    public function test__construct1() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
