<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-06-26 at 11:42:09.
 */
class PhotoUtilityTest extends PHPUnit_Framework_TestCase {

    /**
     * @var PhotoUtility
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new PhotoUtility;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers PhotoUtility::createThumbs
     * @todo   Implement testCreateThumbs().
     */
    public function testCreateThumbs() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PhotoUtility::createThumb_old
     * @todo   Implement testCreateThumb_old().
     */
    public function testCreateThumb_old() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PhotoUtility::createThumb
     * @todo   Implement testCreateThumb().
     */
    public function testCreateThumb() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PhotoUtility::createGallery
     * @todo   Implement testCreateGallery().
     */
    public function testCreateGallery() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
