<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-06-26 at 11:42:08.
 */
class UtilityTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Utility
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Utility;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Utility::createRandomPassword
     * @todo   Implement testCreateRandomPassword().
     */
    public function testCreateRandomPassword() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Utility::convertMonth
     * @todo   Implement testConvertMonth().
     */
    public function testConvertMonth() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Utility::dateTimeToEnglishFormat
     * @todo   Implement testDateTimeToEnglishFormat().
     */
    public function testDateTimeToEnglishFormat() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Utility::dateTimeToItalianFormat
     * @todo   Implement testDateTimeToItalianFormat().
     */
    public function testDateTimeToItalianFormat() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Utility::dateToItalianFormat
     * @todo   Implement testDateToItalianFormat().
     */
    public function testDateToItalianFormat() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Utility::convertDataForDB
     * @todo   Implement testConvertDataForDB().
     */
    public function testConvertDataForDB() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Utility::getStato
     * @todo   Implement testGetStato().
     */
    public function testGetStato() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Utility::cleanField
     * @todo   Implement testCleanField().
     */
    public function testCleanField() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Utility::codeToHTML
     * @todo   Implement testCodeToHTML().
     */
    public function testCodeToHTML() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Utility::replaceTextBoxBr
     * @todo   Implement testReplaceTextBoxBr().
     */
    public function testReplaceTextBoxBr() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Utility::cleanForLabelGeneration
     * @todo   Implement testCleanForLabelGeneration().
     */
    public function testCleanForLabelGeneration() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Utility::cleanTextAreaQuotes
     * @todo   Implement testCleanTextAreaQuotes().
     */
    public function testCleanTextAreaQuotes() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Utility::convertDateForDB
     * @todo   Implement testConvertDateForDB().
     */
    public function testConvertDateForDB() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Utility::cleanStringJS
     * @todo   Implement testCleanStringJS().
     */
    public function testCleanStringJS() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Utility::cleanForMetatag
     * @todo   Implement testCleanForMetatag().
     */
    public function testCleanForMetatag() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Utility::curPageURL
     * @todo   Implement testCurPageURL().
     */
    public function testCurPageURL() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Utility::getDeviceType
     * @todo   Implement testGetDeviceType().
     */
    public function testGetDeviceType() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Utility::getServerOS
     * @todo   Implement testGetServerOS().
     */
    public function testGetServerOS() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Utility::makeFriendlyUrl
     * @todo   Implement testMakeFriendlyUrl().
     */
    public function testMakeFriendlyUrl() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Utility::removeAccent
     * @todo   Implement testRemoveAccent().
     */
    public function testRemoveAccent() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Utility::date_mysqltoscreen
     * @todo   Implement testDate_mysqltoscreen().
     */
    public function testDate_mysqltoscreen() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
