<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-06-26 at 11:42:07.
 */
class UtilityIOTest extends PHPUnit_Framework_TestCase {

    /**
     * @var UtilityIO
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new UtilityIO;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers UtilityIO::removeDirectory
     * @todo   Implement testRemoveDirectory().
     */
    public function testRemoveDirectory() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers UtilityIO::removeFile
     * @todo   Implement testRemoveFile().
     */
    public function testRemoveFile() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers UtilityIO::replaceInFile
     * @todo   Implement testReplaceInFile().
     */
    public function testReplaceInFile() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers UtilityIO::unzipFile
     * @todo   Implement testUnzipFile().
     */
    public function testUnzipFile() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers UtilityIO::uploadFile
     * @todo   Implement testUploadFile().
     */
    public function testUploadFile() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers UtilityIO::chmod
     * @todo   Implement testChmod().
     */
    public function testChmod() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
