<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-06-26 at 11:42:07.
 */
class WebUtilityTest extends PHPUnit_Framework_TestCase {

    /**
     * @var WebUtility
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new WebUtility;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers WebUtility::addDl
     * @todo   Implement testAddDl().
     */
    public function testAddDl() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers WebUtility::createOptions
     * @todo   Implement testCreateOptions().
     */
    public function testCreateOptions() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers WebUtility::createOptionsCheckBox
     * @todo   Implement testCreateOptionsCheckBox().
     */
    public function testCreateOptionsCheckBox() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers WebUtility::addcheckbox
     * @todo   Implement testAddcheckbox().
     */
    public function testAddcheckbox() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers WebUtility::generate_calendar
     * @todo   Implement testGenerate_calendar().
     */
    public function testGenerate_calendar() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers WebUtility::generate_orizzontal_calendar
     * @todo   Implement testGenerate_orizzontal_calendar().
     */
    public function testGenerate_orizzontal_calendar() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers WebUtility::NoHtml
     * @todo   Implement testNoHtml().
     */
    public function testNoHtml() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
