<?php

namespace ridesoft\Boiler\application;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-07-02 at 17:06:21.
 */
class baseControllerTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var baseController
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new baseController;
        $this->assertInstanceOf('ridesoft\Boiler\application\baseController', $this->object);
    }

}
