<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-06-26 at 11:42:06.
 */

use ridesoft\Boiler\application\Registry;

class RegistryTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Registry
     */
    protected $object;
    
    
    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     * 
     * @group annotation
     */
    protected function setUp() {
        $this->object = new Registry;
        $this->assertInstanceOf('ridesoft\Boiler\application\Registry', $this->object);
        $this->assertObjectHasAttribute("vars", $this->object);
        
    }

    

    /**
     * @covers Registry::__set
     * @dataProvider provider
     * @group annotation
     */
    public function test__set($field,$value) {
       $this->object->$field = $value;
       $this->assertEquals($this->object->$field,$value);
    }

    /**
     * @covers Registry::__get
     * @depends test__set
     * @dataProvider provider
     * @group annotation
     */
    public function test__get($field,$value) {
        $this->test__set($field, $value);
        $this->assertEquals($this->object->$field,$value);
    }
    
    public function provider()
    {
        return array(
            array("nome","maurizio"),
            array("cognome","brioschi"),
            array("1","344"),
            
            );
       
    }
    

}
