<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-06-26 at 11:42:06.
 */

use ridesoft\Boiler\application\router;


class routerTest extends PHPUnit_Framework_TestCase {

    /**
     * @var router
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     * @group annotation
     */
    protected function setUp() {
        $this->object = new router(new \ridesoft\Boiler\application\Registry);
        $this->assertInstanceOf('ridesoft\Boiler\application\router', $this->object);
        $this->assertObjectHasAttribute("registry", $this->object);
        $this->assertObjectHasAttribute("path", $this->object);
        $this->assertObjectHasAttribute("args", $this->object);
        $this->assertObjectHasAttribute("file", $this->object);
        $this->assertObjectHasAttribute("controller", $this->object);
        $this->assertObjectHasAttribute("action", $this->object);
       
    }


    /**
     * @covers router::loader
     * @dataProvider provider
     * @group annotation
     */
    public function testLoader($route,$expectedFile,$expectedController,$expectedAction) {
        $this->object->setPath(__SITE_PATH . '/controller/');
        $_GET = $route;
        $this->object->loader();
        $this->assertEquals($this->object->controller,$expectedController);
        $this->assertEquals($this->object->file,$expectedFile);
        $this->assertEquals($this->object->action,$expectedAction);
    }
    
    public function provider() {
        return array(
            array("index.php", __SITE_PATH ."/controller/indexController.php","index","index"),
            array("index.php?rt=home",__SITE_PATH ."/controller/indexController.php","index","index")
            );
    }

}
